#!/bin/bash

homedir=~
eval homedir=$homedir

cd $homedir/workspace/sport-sandbox/sport
git pull -p
git checkout feature_SPORTSDATA-4764_dsp_to_ldp_football_tables

cd $homedir/workspace/sport-sandbox/onesport
git pull -p
git checkout feature_SPORTSDATA-4764_dsp_to_ldp_football_tables

cd $homedir/workspace/sport-sandbox/bbc-pal-library-onesport
git pull -p
git checkout feature_SPORTSDATA-4764_dsp_to_ldp_football_tables